### ISSUE TITLE
Update dependency to react-helmet 6.1 to avoid a warning on the console

### ISSUE THREAD

**Issue by ReactAcademyCa** [3nvi/gatsby-intl#13]
With **gatsby-theme-intl**, in **package.json**, you have a dependency on `"react-helmet": "^5.2.1"`.

Because of this, I get the following warning on the browser console:

> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: SideEffect(NullComponent)

To avoid this problem, we should update to react-helmet 6.1 or higher.

**Comment by 3nvi** [comment]
Yup, sure thing

**Comment by 3nvi** [comment]
Fixes in `0.4.13`
