### ISSUE TITLE
gatsby-offline stops working when using gatby-theme-intl

### ISSUE THREAD

**Issue by figgew** [3nvi/gatsby-intl#15]
I'm unable to get the gatsby-offline plugin to cache any pages when using gatsby-theme-intl. The build process generates the following warning:

```
warn One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "public",
  "globPattern": "offline-plugin-app-shell-fallback/index.html",
  "globIgnores": [
    "**/workbox-v4.3.1/*.+(js|mjs)*",
    "**/node_modules/**/*",
    "**/sw.js"
  ]
}
info Generated public/sw.js, which will precache 0 files, totaling 0 bytes.
```

**Comment by 3nvi** [comment]
Hey @figgew , 

Thanks for opening this. My guess is that you'll need to change the configuration in your `gatsby-offline` plugin to account for the dynamically created URLs (i..e `/en/index.html` , `/fr/index.html`, etc.) since the simple `/index.html` won't be there anymore (`gatsby-theme-intl` creates a redirect from it to one of the localized versions shown before depending on the user's browser language preferences)

I'll review it and get back to you soon, but in the meantime, any additional info or experimentation would greatly help.

**Comment by figgew** [comment]
Hi, thanks for answering so quickly - I think you’re right, and I’ve been trying to figure out different ways of configuring the offline plugin, but haven’t succeeded yet - tried to add different pages to the offline precache but to no avail, also tried to override globpatterns

resolve: `gatsby-plugin-offline`,
      options: {
        precachePages: [`/en/index.html`],
      }

Still getting this though:

warn One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "public",
  "globPattern": "offline-plugin-app-shell-fallback/index.html",
  "globIgnores": [
    "**/workbox-v4.3.1/*.+(js|mjs)*",
    "**/node_modules/**/*",
    "**/sw.js"
  ]
}
info Generated public/sw.js, which will precache 0 files, totaling 0 bytes.
The following pages will be precached:
/offline-plugin-app-shell-fallback/index.html
/en/index.html

**Comment by 3nvi** [comment]
Interesting. I've never used the offline plugin so it might take a tiny bitt of time for me to resolve this, but I'll definitely keep you posted on this.

Thanks for the help so far

**Comment by figgew** [comment]
Hi,

I tried to replicate the issue by installing the standard Gatsby starter, adding the offline plugin and then gatsby-theme-intl, and the problem appears straight away.

Let me know if there's anything I can do to help

**Comment by 3nvi** [comment]
Hey @figgew , I'll spend some time today and get back to you with updates

**Comment by 3nvi** [comment]
Hey @figgew , turns out it's easier than expected. Given the fact that `gatsby-plugin-offline` accepts globs, you can just pass all translated pages by adding:

```js
{
      resolve: `gatsby-plugin-offline`,
      options: {
        precachePages: [`/en/*`, `/fr/*`],
      },
}
```

If instead what you want it to only cache a specific page, you can change the value of `precachePages` to 
`precachePages: ['/en/news/index.html', '/fr/news/index.html']`.

 The reason that `precachePages: [`/en/index.html`]` was not working for you is that  - for some reason - the plugin expects to find the roott page at `/en//index.html` for some reason (notice the double slash).
 
 In any case, the glob pattern has you covered. Let me know if you find any further problems. In the meantime, I'll be closing this one :)

**Comment by figgew** [comment]
Thanks so much! I tried everything EXCEPT adding the * at the end... :)

**Comment by figgew** [comment]
Hi again - unfortunately, it seems this solution doesn't work... I tried it in the minimal setup above and it still gives a similar answer:

info Generated public/sw.js, which will precache 0 files, totaling 0 bytes.
The following pages will be precached:
/offline-plugin-app-shell-fallback/index.html
/en/404/index.html
/en/index.html
/en/offline-plugin-app-shell-fallback/index.html
/en/page-2/index.html
/en/using-typescript/index.html

Seems to me that the generated service worker js file (sw.js) still references /offline-plugin-app-shell-fallback, which now doesn't exist. Not sure that's the whole reason for this happening, though. Did you get it to work?

**Comment by figgew** [comment]
Hi again - just wanted to check if you had any chance to look at this, I unfortunately cannot get this working.

**Comment by 3nvi** [comment]
Hey @figgew , `gatsby-plugin-offline` is a little bit confusing when having a multi-language website. You don't necessarily have a single app-shell fallback for all translations, but if you're comfortable with just having one app shell for all languages, you should tell `gatsby-theme-intl` not to mess with the HTML file that `gatsby-plugin-offline` creates. You can achieve this like so:


```js
{
      resolve: '@3nvi/gatsby-theme-intl',
      options: {
        // ... rest of your config
        excludedPages: ['/offline-plugin-app-shell-fallback/'],  // <-- add this line
      },
    },
```

Make sure you keep the config of `gatsby-plugin-offline` as instructed in the comments above and everything should be working. Let me know how that goes 😃

**Comment by figgew** [comment]
Works like a charm! Thanks for helping out with this, much appreciated!On Sun, Mar 28, 2021 at 7:54pm, Aggelos Arvanitakis ***@***.***> wrote:

Hey @figgew , gatsby-plugin-offline is a little bit confusing when having a multi-language website. You don't necessarily have a single app-shell fallback for all translations, but if you're comfortable with just having one app shell for all languages, you should tell gatsby-theme-intl not to mess with the HTML file that gatsby-plugin-offline creates. You can achieve this like so:

{

      resolve: ***@***.***/gatsby-theme-intl',

      options: {

        // ... rest of your config

        excludedPages: ['/offline-plugin-app-shell-fallback/'],  // <-- add this line

      },

    },

Make sure you keep the config of gatsby-plugin-offline as instructed in the comments above and everything should be working. Let me know how that goes github.githubassets.com/images/icons/emoji/unicode/1f603.png" style="">😃



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/3nvi/gatsby-intl/issues/15#issuecomment-808932408",

"url": "https://github.com/3nvi/gatsby-intl/issues/15#issuecomment-808932408",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by 3nvi** [comment]
Cheers :)
