### ISSUE TITLE
Possible bug in gatsby-theme-intl

### ISSUE THREAD

**Issue by alveshelio** [3nvi/gatsby-intl#6]
Hi @3nvi,

I'm getting these errors in the console: `Cannot update a component ('IndexPage') while rendering a different component ('PageRenderer'). To locate the bad setState() call inside 'PageRenderer',`
`The route "/" matches both a page and a redirect; this is probably not intentional.`

For the first error, could it be happening because how `gatsby-theme-intl` is providing context? According to this article: https://markoskon.com/wrap-root-element-vs-wrap-page-element/, it says that we can use `wrapPageElement` for everything but `wrapPageElement` should be used for providers that require router props and `wrapRootElement` for any other provider, like theme and global state providers.

Could this error be happening because where we are wrapping page element that rerenders every time while `wrapRootElement` only renders once?

When I clone `gatsby-starter-intl`, both these errors are present.

The problem with this error: `The route "/" matches both a page and a redirect; this is probably not intentional.`, could it be that we are not removing the trailing slash? In Gatsby's example for i18n here: https://github.com/gatsbyjs/gatsby/blob/master/examples/using-i18n/gatsby-node.js they are removing the trailing slash.

**Comment by 3nvi** [comment]
This is actually an issue with Gatsby.

Please view this [issue and the related thread](https://github.com/gatsbyjs/gatsby/issues/18665)

To fix it, [a PR was merged recently](https://github.com/gatsbyjs/gatsby/pull/19789), but the issue still persists. The PR didn't correctly handle pages that are dynamically deleted (as is with the case of `gatsby-plugin-intl`).

To verify that, run `npm run build` and you will see that neither `index.js` (i.e. `/`) nor `app.js` (i.e. `/app/`) are present in the `build` folder. This means that during build-time, Gatsby correctly handles the dynamic deletion that `gatsby-plugin-intl` performs.

During development though, Gatsby **wrongly** assumes that the pages are still there (cause the checks don't account for dynamically deleted pages), so it issues a false warning. This is clearly mentioned in the issue I linked above. From my side there is nothing i can do :/

**Comment by alveshelio** [comment]
Thank you for your return.
