### ISSUE TITLE
Add copyright notice to license

### ISSUE THREAD

**Issue by balibebas** [3nvi/gatsby-intl#8]
This is a great starter but as it stands the work added to the `gatsby-starter-default` is unclear from a licensing perspective given no copyright notice was added by the author. Please add a copyright notice. For more information see: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html. If you're unsure how to add a notice let me know and I'll help.

Related: https://github.com/gatsbyjs/gatsby/issues/25091

**Comment by 3nvi** [comment]
Given my limited knowledge on the topic, could you  provide some additional information on the actionable items that you wish to be performed in this repo?

I saw the related issue that you opened on the Gatsby repo, but I  want to  understand what should be done while the default starter is still licensed under MIT.

**Comment by balibebas** [comment]
Wow, you're fast. Thanks for responding. If you follow the link in the upstream issue to the Shopify starter, you can see how we handled it.

**Comment by 3nvi** [comment]
Thanks for letting me know. Much appreciated!
