### ISSUE TITLE
SEO makes plugin too opinionated

### ISSUE THREAD

**Issue by balibebas** [3nvi/gatsby-intl#9]
SEO is very personal and should be handled in userland. If anything, please provide a disable option in the plugin and instructions for userland integration into sites' own SEO components.

**Comment by 3nvi** [comment]
This plugin adds just the core SEO  tags that are associated with itself. I agree with you, but the tags that are added here, are **only** the ones related to the way the plugin operates.

If you create a multi-page  website  through this plugin, then you are creating multiple static pages with an opinionated URL prefixing. This mandates the need for proper SEO linking between the two, which not only  mandatory but has a  **standardized** implementation.

At  the  end of the  day, you can still add any additional SEO tags you want. If you wanted the translation-related SEO tags gone, I don't know if you should be using the plugin  to begin with.

Feel free to correct me if I'm missing something

**Comment by balibebas** [comment]
Given the following three scenarios:

- I have an existing site using `react-helmet` and hand-rolled SEO component
- I have an existing site usng `react-head` and a hand-rolled SEO component
- I have an existing site using `react-helmet-async` via a plug-in

Would one be able to customize things the plug-in (or theme) was doing via shadow components or by disabling it (in the case of a clash between SEO tooling de jour?

**Comment by 3nvi** [comment]
I am failing to see how this would create any issues. Would you be re-writing the **particular** SEO tags generated by this plugin? 

If not, you shouldn't have any problems.

If yes, please explain why & what were you trying to achieve, since these are tied to the plugin's core functionality, so any additional intl-related meta tag might need be part of this plugin in the first place.

Cheers!

**Comment by balibebas** [comment]
Will close for now until I get that far. I'm looking ahead for potential roadblocks. Seems i18n shouldn't dictate how one updates `head` as I'm not settled on Helmet. Thanks for your time. :pray:
